### ISSUE TITLE
[idea] Introduce private links via encrypted datastore

### ISSUE THREAD

**Issue by captn3m0** [captn3m0/lightsaber#1]
The idea is that anyone can add an encrypted entry in `redirects.yml`, but the entry can only be validated/read by lightsaber while in deployment.

We can give out a route that lets people easily encrypt content as well.

**Comment by captn3m0** [comment]
This could look something like:

``` yml
encrypted:
  - fix.google.com:
      location: https://google.com
      status: 302
      root: https://twitter.com
```

This makes each entry an element in the list, instead of a map. Each entry could be serialized and encrypted separately. (Which gives us a list of strings, which can be decrypted and deserialized to give us the original list of maps).

We merge this with the original to give us a complete redirect map.
